version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
  server-backend:
    image: golang:1.20.7-alpine3.18
    volumes:
      - "${PWD}/backend:/app"
    restart: always
    working_dir: '/app'
    command: sh -c "go run ./main.go"
    ports:
      - "8080:8080"
    depends_on:
      - jaeger
  grpc-backend:
    image: golang:1.20.7-alpine3.18
    volumes:
      - "${PWD}grpc-backend:/app"
    restart: always
    working_dir: '/app'
    command: sh -c "go run ./main.go"
    ports:
      - "8081:8081"
    depends_on:
      - jaeger
