// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpc-backend/pkg/proto/server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GRPCBackendClient is the client API for GRPCBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCBackendClient interface {
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
}

type gRPCBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCBackendClient(cc grpc.ClientConnInterface) GRPCBackendClient {
	return &gRPCBackendClient{cc}
}

func (c *gRPCBackendClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/proto_grpc_server.GRPCBackend/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCBackendServer is the server API for GRPCBackend service.
// All implementations must embed UnimplementedGRPCBackendServer
// for forward compatibility
type GRPCBackendServer interface {
	Test(context.Context, *TestRequest) (*TestResponse, error)
	mustEmbedUnimplementedGRPCBackendServer()
}

// UnimplementedGRPCBackendServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCBackendServer struct {
}

func (UnimplementedGRPCBackendServer) Test(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedGRPCBackendServer) mustEmbedUnimplementedGRPCBackendServer() {}

// UnsafeGRPCBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCBackendServer will
// result in compilation errors.
type UnsafeGRPCBackendServer interface {
	mustEmbedUnimplementedGRPCBackendServer()
}

func RegisterGRPCBackendServer(s grpc.ServiceRegistrar, srv GRPCBackendServer) {
	s.RegisterService(&GRPCBackend_ServiceDesc, srv)
}

func _GRPCBackend_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCBackendServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_grpc_server.GRPCBackend/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCBackendServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCBackend_ServiceDesc is the grpc.ServiceDesc for GRPCBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto_grpc_server.GRPCBackend",
	HandlerType: (*GRPCBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _GRPCBackend_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-backend/pkg/proto/server.proto",
}
